receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 10s
    send_batch_size: 1024

  memory_limiter:
    check_interval: 1s
    limit_mib: 512

exporters:
  # Send traces to Tempo via internal Docker network
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true

  # Debug exporter for troubleshooting
  debug:
    verbosity: detailed

service:
  # Expose internal telemetry metrics for Prometheus scraping
  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: '0.0.0.0'
                port: 8888
  
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp, debug]
