receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 10s
    send_batch_size: 1024

  memory_limiter:
    check_interval: 1s
    limit_mib: 512

exporters:
  # Send traces to Tempo via internal Docker network
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true

  # Optional: Send metrics to Prometheus (if needed)
  # prometheus:
  #   endpoint: "0.0.0.0:8889"

  # Debug exporter for troubleshooting
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp, debug]

    # Uncomment if you want to forward metrics through OTel
    # metrics:
    #   receivers: [otlp]
    #   processors: [memory_limiter, batch]
    #   exporters: [prometheus]
