modules:
  # HTTP 2xx probe - checks if endpoint returns 200-299 status
  http_2xx:
    prober: http
    timeout: 5s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      valid_status_codes: []  # Defaults to 2xx
      method: GET
      preferred_ip_protocol: "ip4"
      follow_redirects: true

  # HTTPS with TLS verification
  https_2xx:
    prober: http
    timeout: 5s
    http:
      valid_status_codes: []
      method: GET
      tls_config:
        insecure_skip_verify: false

  # TLS certificate expiry check
  tls_connect:
    prober: tcp
    timeout: 5s
    tcp:
      tls: true
      tls_config:
        insecure_skip_verify: false

  # TCP connection check
  tcp_connect:
    prober: tcp
    timeout: 5s

  # ICMP ping check
  icmp:
    prober: icmp
    timeout: 5s
    icmp:
      preferred_ip_protocol: "ip4"
